name: Release docs
run-name: Releasing docs by @${{ github.actor }}

# temporary solution to test without merging to main
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout arcane-operator (main)
        uses: actions/checkout@v4
        with:
          repository: SneaksAndData/arcane-operator
          path: arcane-operator-main

      - name: Checkout arcane-operator (previous release)
        uses: actions/checkout@v4
        with:
          repository: SneaksAndData/arcane-operator
          path: arcane-operator-previous
          fetch-depth: 0

      - name: Determine previous release commit for arcane-operator
        run: |
          cd arcane-operator-previous
          git fetch --tags
          SECOND_LAST_TAG=$(git tag --sort=-version:refname | tail -n 2 | head -1)
          echo "Checking previous out tag: $SECOND_LAST_TAG"
          echo "$SECOND_LAST_TAG" > SECOND_LAST_TAG.txt
          git checkout $SECOND_LAST_TAG

      - name: Modify toc.yml with tags for arcane-operator
        run: |
          cd ${{ github.workspace }}
          TAG=$(cat arcane-operator-previous/SECOND_LAST_TAG.txt) 
          echo "Checking previous out tag: $TAG"
          sed -i "s|- name: previous release|- name: $TAG|g" toc.yml

      - name: Checkout arcane-framework (main)
        uses: actions/checkout@v4
        with:
          repository: SneaksAndData/arcane-framework
          path: arcane-framework-main

      - name: Checkout arcane-framework (previous release)
        uses: actions/checkout@v4
        with:
          repository: SneaksAndData/arcane-framework
          path: arcane-framework-previous
          fetch-depth: 0

      - name: Determine previous release commit for arcane-framework
        run: |
          cd arcane-framework-previous
          git fetch --tags
          SECOND_LAST_TAG=$(git tag --sort=-version:refname | tail -n 2 | head -1)
          echo "Checking previous out tag: $SECOND_LAST_TAG"
          echo "SECOND_LAST_TAG=$SECOND_LAST_TAG" > SECOND_LAST_TAG.txt
          git checkout $SECOND_LAST_TAG

      - name: Modify toc.yml with tags for arcane-framework
        run: |
          cd ${{ github.workspace }}
          TAG=$(cat arcane-framework-previous/SECOND_LAST_TAG.txt) # Assuming you save the tag in a file
          sed -i "s|- name: previous release|- name: $TAG|g" toc.yml

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.0.0

      - name: Setup DocFX
        run: dotnet tool update -g docfx

      - name: DocFX Build
        run: docfx docfx.json
        continue-on-error: false

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "./_site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Print Page URL
        run: echo "Github Pages URL ${{ steps.deployment.outputs.page_url }}"
