name: Release docs
run-name: Releasing by @${{ github.actor }}

# temporary solution to test without merging to main
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self
        uses: actions/checkout@v4

      - name: Checkout arcane-operator (latest release)
        uses: actions/checkout@v4
        with:
          repository: SneaksAndData/arcane-operator
          path: arcane-operator-latest

      - name: Checkout arcane-operator (previous release)
        uses: actions/checkout@v4
        with:
          repository: SneaksAndData/arcane-operator
          path: arcane-operator-previous
          fetch-depth: 0

      - name: Determine previous release commit
        run: |
          cd arcane-operator-previous
          git fetch --depth=100 
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 HEAD^)
          echo "Previous release tag: $PREVIOUS_TAG"
          git checkout $PREVIOUS_TAG
        id: prev_release

      - name: Checkout arcane-framework (latest release)
        uses: actions/checkout@v4
        with:
          repository: SneaksAndData/arcane-framework
          path: arcane-framework-latest

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.0.0

      - name: Setup DocFX
        run: dotnet tool update -g docfx

      - name: DocFX Build
        run: docfx docfx.json
        continue-on-error: false

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "./_site"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Print Page URL
        run: echo "Github Pages URL ${{ steps.deployment.outputs.page_url }}"
